language: generic
sudo: required
services:
    #tell TravisCI to install docker
    - docker

before_install:
    #-t cicd tags image; use instead of image id
    - docker build -t cicd -f Dockerfile.dev .

script:
    - docker run -e CI=true cicd npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "demo"
    env: "Demo-env"
    bucket_name: "elasticbeanstalk-us-east-1-354456256274"
    bucket_path: "demo"
    on:
        # only deploy when master branch gets new code
        branch: master

    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY